### ISSUE TITLE
Error: Cannot find module 'yeoman-generator/node_modules/glob'

### ISSUE THREAD

**Issue by tdespenza** [ahmed-masud/yo-express-polymer#3]
When I run `yo polymer-express`, I get the error in the title.

Full stacktrace:

```
module.js:328
    throw err;
    ^

Error: Cannot find module 'yeoman-generator/node_modules/glob'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/tdespenza/.nvm/versions/node/v5.4.0/lib/node_modules/generator-polymer-express/generators/app/index.js:9:12)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
```

Running 
- nvm = 0.30.1
- node = v5.4.0
- npm = 3.3.12

I reinstalled the generator, node and yo but it still doesn't work. Any clues on how to get this working?

**Comment by ahmed-masud** [comment]
Hey, there are a number of issues in this version. I need to spend some time to fix them.

**Comment by tdespenza** [comment]
No worries. Thanks for the response.

**Comment by DCUnit711** [comment]
Any sort of eta on getting this working again?
